import { Database, Monitor, Network, Server, Shield } from 'lucide-react';
import type { AssetType } from '../../types/diagram';

export const assetTypeIconMap: Record<AssetType, typeof Server> = {
  防火墙: Shield,
  日志审计: Monitor,
  数据库审计: Database,
  堡垒机: Shield,
  VPN: Shield,
  IPS: Shield,
  IDS: Shield,
  EDR: Monitor,
  上网行为管理: Monitor,
  态势感知: Monitor,
  探针: Monitor,
  交换机: Network,
  路由器: Network,
  网关: Network,
  单台服务器: Server,
  服务器集群: Server,
  数据库: Database,
  其他设备: Server,
  Firewall: Shield,
  Switch: Network,
  Server,
  Database,
  Terminal: Monitor,
  Custom: Server,
};

export const assetTypeColorMap: Record<AssetType, string> = {
  防火墙: 'text-rose-600 bg-rose-50 border-rose-200',
  日志审计: 'text-amber-600 bg-amber-50 border-amber-200',
  数据库审计: 'text-emerald-600 bg-emerald-50 border-emerald-200',
  堡垒机: 'text-rose-600 bg-rose-50 border-rose-200',
  VPN: 'text-cyan-600 bg-cyan-50 border-cyan-200',
  IPS: 'text-fuchsia-600 bg-fuchsia-50 border-fuchsia-200',
  IDS: 'text-pink-600 bg-pink-50 border-pink-200',
  EDR: 'text-violet-600 bg-violet-50 border-violet-200',
  上网行为管理: 'text-amber-600 bg-amber-50 border-amber-200',
  态势感知: 'text-indigo-600 bg-indigo-50 border-indigo-200',
  探针: 'text-sky-600 bg-sky-50 border-sky-200',
  交换机: 'text-sky-600 bg-sky-50 border-sky-200',
  路由器: 'text-blue-600 bg-blue-50 border-blue-200',
  网关: 'text-cyan-600 bg-cyan-50 border-cyan-200',
  单台服务器: 'text-violet-600 bg-violet-50 border-violet-200',
  服务器集群: 'text-indigo-600 bg-indigo-50 border-indigo-200',
  数据库: 'text-emerald-600 bg-emerald-50 border-emerald-200',
  其他设备: 'text-slate-600 bg-slate-50 border-slate-200',
  Firewall: 'text-rose-600 bg-rose-50 border-rose-200',
  Switch: 'text-sky-600 bg-sky-50 border-sky-200',
  Server: 'text-violet-600 bg-violet-50 border-violet-200',
  Database: 'text-emerald-600 bg-emerald-50 border-emerald-200',
  Terminal: 'text-amber-600 bg-amber-50 border-amber-200',
  Custom: 'text-slate-600 bg-slate-50 border-slate-200',
};
